In [ ]:
作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [1]:
import numpy as np

In [9]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
print('陣列:\n', array1)

陣列:
 [[10  8]
 [ 3  5]]


In [11]:
array1_inv = np.linalg.inv(array1)
print('反矩陣(inverse):\n', array1_inv)

反矩陣(inverse):
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]


In [46]:
array1_matmul = np.matmul(array1, array1_inv)
print('反矩陣乘上原矩陣是否為單位矩陣(identity):\n', array1_matmul)
array1_matmul.astype(int)

反矩陣乘上原矩陣是否為單位矩陣(identity):
 [[1. 0.]
 [0. 1.]]


array([[0, 0],
       [0, 1]])

In [43]:
array1_dot = np.dot(array1_inv, array1)
print(array1_dot)

[[1. 0.]
 [0. 1.]]


In [23]:
#2. 運用上列array計算特徵值、特徵向量?
np.linalg.eigvals(array1)
print('計算特徵值(eigenvalue): ', np.linalg.eigvals(array1))

計算特徵值(eigenvalue):  [13.  2.]


In [33]:
eigenvalue, eigenvector = np.linalg.eig(array1)
print('特徵值eigenvalue: \n', eigenvalue)
print('特徵量eigenvector: \n', eigenvector)

特徵值eigenvalue: 
 [13.  2.]
特徵量eigenvector: 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [35]:
#3. 運用上列array計算SVD?
print('奇異值SVD(singular value decomposition): \n', np.linalg.svd(array1))

奇異值SVD(singular value decomposition): 
 (array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]]), array([13.94721714,  1.86417116]), array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]]))
